name: automerge
on:
  pull_request:
    branches: [staging, canary, main]
    types:
      - opened
      - edited
      - reopened

  pull_request_review:
    types:
      - submitted
  check_run:
    types:
      - completed
  check_suite:
    types:
      - completed
  status: ~

concurrency:
  group: automerge

jobs:
  merge-ff-only:
    runs-on: ubuntu-latest

    steps:
      - name: Find matching, mergeable PRs
        uses: actions/github-script@v7
        id: find-pr
        with:
          script: |
            const openPRs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open",
            });
            let pr = openPRs.data.find(pr => ['staging', 'canary', 'main'].includes(pr.base.ref) &&  pr.head.sha === context.sha);
            if (pr.length !== 1) {
              return false;
            }
            pr = pr[0];
            if (pr.rebaseable && pr.mergeable_state === "clean") {
              return pr;
            }
            return false;
      - uses: actions/checkout@v4
        if: ${{ steps.find-pr.outputs.result }}
        with:
          ref: ${{ steps.find-pr.outputs.result.base.ref }}
          fetch-depth: 0
      - name: Merge PR with --ff-only
        if: ${{ steps.find-pr.outputs.result }}
        run: |
          git merge --ff-only ${{ steps.find-pr.outputs.result.head.ref }}
          git push origin ${{ steps.find-pr.outputs.result.base.ref }}
