name: promote

on:
  workflow_call:
    inputs:
      stages:
        required: false
        type: string
        default: '["develop", "staging:auto", "canary", "main"]'

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        id: calculate-promotion
        env:
          STAGES: ${{ toJson(fromJSON(inputs.stages)) }}
        with:
          github-token: "not-used"
          script: |
            const stages = JSON.parse(process.env.STAGES)
            const stagesMap = stages.reduce((map, stage) => {
              const splitStage = stage.split(":");
              map.set(splitStage[0], splitStage[1] ? splitStage[1] === "auto" : false);
              return map;
            }, new Map());
            const stagesArray = Array.from(stagesMap.keys());
            const currentIndex = stagesArray.indexOf(github.ref_name);
            const currentStage = stagesArray[currentIndex];
            const targetIndex = (currentIndex !== -1 && currentIndex < stagesArray.length - 1 ) ? currentIndex + 1 : null;
            const targetStage = targetIndex !== null ? stagesArray[targetIndex] : null;
            const autoPromote = targetStage !== null ? stagesMap.get(targetStage) : false;
            return {
              currentStage,
              targetStage,
              autoPromote
            };
          # result-encoding: string
      - name: Get result
        run: echo "${{steps.calculate-promotion.outputs.result}}"
