name: promotion

on:
  push:
    branches:
      - develop
  pull_request_review:
    types: [submitted]
  check_run:
    types: [completed]
  check_suite:
    types: [completed]
  deployment_status: ~
  status: ~

permissions:
  contents: write
  pull-requests: write
  statuses: write

concurrency:
  group: promotion

jobs:
  initiate:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Request Promotion
        uses: ./.github/actions/open-promotion-request
        with:
          stages: '["develop", "staging:auto", "canary", "main"]'
          source: "${{ github.ref }}"

  progress:
    if: ${{ github.event_name != 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: Find Promotion Request
        id: find
        uses: ./.github/actions/find-promotion-request
        with:
          targetRefs: '["staging", "canary", "main"]'
      - name: Fast-Forward Merge
        id: merge
        if: ${{ steps.find.outputs.found }}
        uses: ./.github/actions/fast-forward-merge
        with:
          baseRef: ${{ steps.find.outputs.baseRef }}
          headRef: ${{ steps.find.outputs.headRef }}
      - name: Request Promotion
        id: promote
        if: ${{ steps.find.outputs.found }}
        uses: ./.github/actions/open-promotion-request
        with:
          stages: '["develop", "staging:auto", "canary", "main"]'
          source: ${{ steps.find.outputs.baseRef }}
