name: promote

on:
  workflow_call:
    inputs:
      stages:
        required: false
        type: string
        default: '["develop", "staging:auto", "canary", "main"]'

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        env:
          STAGES: ${{ toJson(fromJSON(inputs.stages)) }}
        with:
          github-token: "not-used"
          script: |
            const stages = JSON.parse(process.env.STAGES)
            console.log(stages)
            let foo = stages.forEach((stage) => console.log(`::set-output name=${stage}::${stage}`))
            console.log(`ref_name = ${github.ref_name}`)
          # console.log(`inputs => ${inputs['stages']}`)
          # const stages = core.getMultilineInput("stages")
          # console.log(`stages => ${stages}`)
          # stages.forEach(stage => {
          #   console.log(`::set-output name=${stage}::${stage}`)
          # })
          # return stages
          # result-encoding: string
      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"
