name: trigger-promotion
permissions:
  contents: read
  pull-requests: write
  statuses: write

on:
  push:
    branches:
      - develop

jobs:
  request-promotion:
    uses: ./.github/workflows/request-promotion.yaml
    with:
      stages: '["develop", "staging:auto", "canary", "main"]'
      source: "${{ github.ref }}"
